# Lambda Docker Executor Configuration

# Server configuration
server_address = "0.0.0.0"
port = 3000

# Storage configuration
storage_path = "./functions"

# Docker configuration
[docker_config]
network_name = "lambda-network"
container_prefix = "lambda-"
container_labels = {}

# Execution configuration
[execution_config]
max_concurrent_executions = 100
max_memory_mb = 256
max_cpu_shares = 1.0

# RIC configuration
[ric_config]
port = 8080
startup_timeout_seconds = 30
shutdown_timeout_seconds = 10

# Lifecycle configuration
[lifecycle_config]
max_idle_time_seconds = 300  # 5 minutes
max_container_age_seconds = 3600  # 1 hour
cleanup_interval_seconds = 60  # 1 minute
max_containers_per_function = 10
max_global_containers = 10  # Global limit across all functions