version: '3.8'

services:
  lambda-runtime-api:
    build: .
    ports:
      - "8084:8084"
    environment:
      - RUST_LOG=info
    command: ["cargo", "run", "--bin", "lambda-runtime-api-server"]
    networks:
      - lambda-network

  lambda-container:
    image: lambda-function-ad80c2e0-aedc-4809-a27b-317361ec87e6
    environment:
      - AWS_LAMBDA_RUNTIME_API=http://lambda-runtime-api:8084
      - HANDLER=index.handler
      - AWS_LAMBDA_FUNCTION_NAME=test-function
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=128
    depends_on:
      - lambda-runtime-api
    networks:
      - lambda-network

networks:
  lambda-network:
    driver: bridge
